### ISSUE TITLE
Multiple dots in pcapng filename

### ISSUE THREAD

**Issue by maxsharabayko** [mbakholdina/lib-tcpdump-processing#13]
Example file name: `srt_1.4.1_snd-call_rcv-list.pcapng` with multiple dots is not handled correctly.

```
File "\tcpdump_processing\convert.py", line 57, in convert_to_csv
    name, _ = filename.split('.')
ValueError: too many values to unpack (expected 2)
```

The splitting should replace only the last part of the split() function, while all the previous parts should be merged.

Maybe the reverse find is even better: `rfind()`.

**Comment by mbakholdina** [comment]
A duplicate of #9 .
