### ISSUE TITLE
Handle pcap files

### ISSUE THREAD

**Issue by maxsharabayko** [mbakholdina/lib-tcpdump-processing#23]
Some capture files have `*.pcap` instead of `*.pcapng`.
Scripts does not handle this extension. Renaming the pcap file helps.

```
  File "lib-tcpdump-processing/tcpdump_processing/convert.py", line 54, in convert_to_csv
    raise IsNotPcapngFile(
tcpdump_processing.convert.IsNotPcapngFile: srt-frametime-cest.pcap does not correspond to .pcapng file
```

**Comment by mbakholdina** [comment]
Hi @maxsharabayko, fixed by https://github.com/mbakholdina/lib-tcpdump-processing/commit/460a3a2b5559a10ae0f7763e6a8f101116c27d8b. Available in the latest master.
