### ISSUE TITLE
Uninstall Package

### ISSUE THREAD

**Issue by saltarob** [mbakholdina/lib-tcpdump-processing#41]
Thank you so much for this tool. How do I uninstall it on macOS when I don't need it anymore? Thank you.

**Comment by mbakholdina** [comment]
Hi @saltarob ,

It depends on how you've installed the library. If you've followed [the instructions from README](https://github.com/mbakholdina/lib-tcpdump-processing#install-the-library-with-pip), simply delete the `venv` folder and the project folder itself.

**Comment by saltarob** [comment]
Hi Maria,

thank you so much for your answer.
